WIP: Add stricter `Query` types
LastOliveGames/becsy pull request #8
Opened 2021-10-04 09:49 UTC by marionebl

2021-10-04 23:10 UTC, pkaminski requested changes
Thanks for working on this!  Let's use Reviewable for code reviews if you don't mind -- it's my own project that pays the bills, so I'm kinda partial to it.  :smiley: 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/lastolivegames/becsy/8#-:-MlCWvkdEhwNhjHg5LxY:b3y9aku)* status: all files reviewed, 5 unresolved discussions (waiting on @marionebl)

___
*[package.json, line 28 at r1](https://reviewable.io/reviews/lastolivegames/becsy/8#-MlCXIvk3ZMF-Q302p5L:-MlCXIvk3ZMF-Q302p5M:bgbbi2e) ([raw file](https://github.com/lastolivegames/becsy/blob/b0ed61942811e6e4a061c19ec9a0a72d7665aae6/package.json#L28)):*
> ```JSON
>   },
>   "tsd": {
>     "directory": "test-d",
> ```

Would it make sense to call this directory `type-tests` to match the script and the naming pattern for the normal tests directory, or is `test-d` the convention for this tool?  (Another suggestion might be `tests-d`.)
___
*[test-d/query.test-d.ts, line 4 at r1](https://reviewable.io/reviews/lastolivegames/becsy/8#-MlCXkw85IPfnqPQQhka:-MlCXkw85IPfnqPQQhkb:b2ds6db) ([raw file](https://github.com/lastolivegames/becsy/blob/b0ed61942811e6e4a061c19ec9a0a72d7665aae6/test-d/query.test-d.ts#L4)):*
> ```XML
> import {System} from '../src/system';
> 
> test('query has not flavours by default', () => {
> ```

Nit: `not` -> `no`, `flavours` -> `flavors` (throughout).
___
*[test-d/query.test-d.ts, line 4 at r1](https://reviewable.io/reviews/lastolivegames/becsy/8#-MlCXqSxE8wbxPy8D2_C:-MlCXqSxE8wbxPy8D2_D:b-nkxgda) ([raw file](https://github.com/lastolivegames/becsy/blob/b0ed61942811e6e4a061c19ec9a0a72d7665aae6/test-d/query.test-d.ts#L4)):*
> ```XML
> import {System} from '../src/system';
> 
> test('query has not flavours by default', () => {
> ```

Knowing nothing about `tsd`, should these tests be grouped into suites with `describe` or some such?
___
*[test-d/query.test-d.ts, line 20 at r1](https://reviewable.io/reviews/lastolivegames/becsy/8#-MlCY7Vw8KntFgIX1QTx:-MlCY7Vw8KntFgIX1QTy:b-fnh2c9) ([raw file](https://github.com/lastolivegames/becsy/blob/b0ed61942811e6e4a061c19ec9a0a72d7665aae6/test-d/query.test-d.ts#L20)):*
> ```XML
> 
>   class UnusedTestSystem extends System {
>     private q = this.query(b => b.with(A));
> ```

Incidentally, having a `with` or `without` clause in a flavorless query should probably be invalid -- only `using` makes sense in this case.  I'll need to add this check at runtime.
___
*[test-d/query.test-d.ts, line 39 at r1](https://reviewable.io/reviews/lastolivegames/becsy/8#-MlCYpH7B2RNbPYQjHdh:-MlCYpH7B2RNbPYQjHdi:bx2b4jn) ([raw file](https://github.com/lastolivegames/becsy/blob/b0ed61942811e6e4a061c19ec9a0a72d7665aae6/test-d/query.test-d.ts#L39)):*
> ```XML
>     private q = this.query(b => b.with(A));
>     execute() {
>       expectType<ExpectedShape>(this.q);
> ```

I assume this test (and the ones below) don't currently pass?  A `.with` will not add a `current` flavor all by itself.
___
*[test-d/query.test-d.ts, line 50 at r1](https://reviewable.io/reviews/lastolivegames/becsy/8#-MlCZ3R10wlzxyMjhiZe:-MlCZ3R10wlzxyMjhiZf:b-kk79oy) ([raw file](https://github.com/lastolivegames/becsy/blob/b0ed61942811e6e4a061c19ec9a0a72d7665aae6/test-d/query.test-d.ts#L50)):*
> ```XML
> 
>   interface ExpectedShape {
>     current: readonly A[];
> ```

A query's properties will always be lists of entities, not lists of components, so I'm not sure how this is intended to work.  Ditto below.


<!-- Sent from Reviewable.io -->

2021-10-05 08:07 UTC, marionebl reviewed
> *[Reviewable](https://reviewable.io/reviews/lastolivegames/becsy/8)* status: all files reviewed, 4 unresolved discussions (waiting on @pkaminski)

___
*[package.json, line 28 at r1](https://reviewable.io/reviews/lastolivegames/becsy/8#-MlCXIvk3ZMF-Q302p5L:-MlESkvv7YQoNSJf0zfC:bbcbwu3) ([raw file](https://github.com/lastolivegames/becsy/blob/b0ed61942811e6e4a061c19ec9a0a72d7665aae6/package.json#L28)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Would it make sense to call this directory `type-tests` to match the script and the naming pattern for the normal tests directory, or is `test-d` the convention for this tool?  (Another suggestion might be `tests-d`.)
</blockquote></details>

`test-d` is in fact the default, so this config isn't strictly required. I think it makes sense to call it `type-tests` as per your suggestion. I'll change it to be consistent.
___
*[test-d/query.test-d.ts, line 4 at r1](https://reviewable.io/reviews/lastolivegames/becsy/8#-MlCXqSxE8wbxPy8D2_C:-MlETBqP45vtbBaG85uZ:bvmdkty) ([raw file](https://github.com/lastolivegames/becsy/blob/b0ed61942811e6e4a061c19ec9a0a72d7665aae6/test-d/query.test-d.ts#L4)):*
> Knowing nothing about tsd, should these tests be grouped into suites with describe or some such?

I think there is no convention established around this as `tsd` is a pretty nice tool. The `test` function wrappers I use here are not used by the tool in any way, I just use them to provide a description. 

We could achieve the same thing via comments if you prefer, although I like the logical grouping the current variant established. 
___
*[test-d/query.test-d.ts, line 4 at r1](https://reviewable.io/reviews/lastolivegames/becsy/8#-MlCXkw85IPfnqPQQhka:-MlEUTiK3a3sqxBXee3I:b8rh2pe) ([raw file](https://github.com/lastolivegames/becsy/blob/b0ed61942811e6e4a061c19ec9a0a72d7665aae6/test-d/query.test-d.ts#L4)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Nit: `not` -> `no`, `flavours` -> `flavors` (throughout).
</blockquote></details>

Ok, will fix.
___
*[test-d/query.test-d.ts, line 39 at r1](https://reviewable.io/reviews/lastolivegames/becsy/8#-MlCYpH7B2RNbPYQjHdh:-MlETtLKBg54ryf082Dv:b-wnzrzx) ([raw file](https://github.com/lastolivegames/becsy/blob/b0ed61942811e6e4a061c19ec9a0a72d7665aae6/test-d/query.test-d.ts#L39)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I assume this test (and the ones below) don't currently pass?  A `.with` will not add a `current` flavor all by itself.
</blockquote></details>

Yes, all the tests don't pass - they are intended as means to sync about expectations between the two of us at this point. 
___
*[test-d/query.test-d.ts, line 50 at r1](https://reviewable.io/reviews/lastolivegames/becsy/8#-MlCZ3R10wlzxyMjhiZe:-MlEUEjp4scj8FEbzyUx:b8rh2pe) ([raw file](https://github.com/lastolivegames/becsy/blob/b0ed61942811e6e4a061c19ec9a0a72d7665aae6/test-d/query.test-d.ts#L50)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

A query's properties will always be lists of entities, not lists of components, so I'm not sure how this is intended to work.  Ditto below.
</blockquote></details>

Ok, will fix.


<!-- Sent from Reviewable.io -->

2021-10-05 08:08 UTC, marionebl commented
___
*[test-d/query.test-d.ts, line 4 at r1](https://reviewable.io/reviews/lastolivegames/becsy/8#-MlCXqSxE8wbxPy8D2_C:-MlEUmnB8e04Ci__OUvY:b47oikn) ([raw file](https://github.com/lastolivegames/becsy/blob/b0ed61942811e6e4a061c19ec9a0a72d7665aae6/test-d/query.test-d.ts#L4)):*
<details><summary><i>Previously, marionebl (Mario Nebl) wrote…</i></summary><blockquote>

> Knowing nothing about tsd, should these tests be grouped into suites with describe or some such?

I think there is no convention established around this as `tsd` is a pretty nice tool. The `test` function wrappers I use here are not used by the tool in any way, I just use them to provide a description. 

We could achieve the same thing via comments if you prefer, although I like the logical grouping the current variant established. 
</blockquote></details>

~~nice~~ niche


<!-- Sent from Reviewable.io -->

2021-10-05 22:55 UTC, pkaminski reviewed
> *[Reviewable](https://reviewable.io/reviews/lastolivegames/becsy/8)* status: all files reviewed, 4 unresolved discussions (waiting on @marionebl and @pkaminski)

___
*[test-d/query.test-d.ts, line 4 at r1](https://reviewable.io/reviews/lastolivegames/becsy/8#-MlCXqSxE8wbxPy8D2_C:-MlHcC0FBcUASmom6aWU:b-ht3smc) ([raw file](https://github.com/lastolivegames/becsy/blob/b0ed61942811e6e4a061c19ec9a0a72d7665aae6/test-d/query.test-d.ts#L4)):*
<details><summary><i>Previously, marionebl (Mario Nebl) wrote…</i></summary><blockquote>

~~nice~~ niche
</blockquote></details>

I like the test functions, but I take it that `tsd` won't invoke them automatically?  If so, would it be possible to put these tests under Jest's control instead (in `tests/`) and just use `tsd` as a custom assertion provider?  Their docs allude to [using Jest](https://github.com/SamVerschueren/tsd#programmatic-api) but don't really explain how to make it work.
___
*[test-d/query.test-d.ts, line 39 at r1](https://reviewable.io/reviews/lastolivegames/becsy/8#-MlCYpH7B2RNbPYQjHdh:-MlHeLxY5QgPniwzp5U4:bk8748c) ([raw file](https://github.com/lastolivegames/becsy/blob/b0ed61942811e6e4a061c19ec9a0a72d7665aae6/test-d/query.test-d.ts#L39)):*
<details><summary><i>Previously, marionebl (Mario Nebl) wrote…</i></summary><blockquote>

Yes, all the tests don't pass - they are intended as means to sync about expectations between the two of us at this point. 
</blockquote></details>

OK, then my expectation is that this test shouldn't pass, since `current` doesn't get added in by default.  :smile: 


<!-- Sent from Reviewable.io -->

2025-07-15 09:09 UTC, closed without merging